services:
  post:
    image: postgres:14.22-trixie
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    container_name: dz_volume
    volumes:
      - /home/layoshka/docker/dz_docker/data:/data/pg
    ports: 
      - 5432:5432
    networks:
      - my-pg-network
networks:
  my-pg-network:
    driver: bridge